### ISSUE TITLE
OSError when I run run_tracker.py

### ISSUE THREAD

**Issue by naybu128** [suxSx/opensource-tracker#6]
**Describe the bug**
Hi, french student in cognitive science here. I am having trouble while installing your script. I am a beginner in Python (and some kind of beginner in Shell), so I am probably doing it wrong.

While installing optracker, using git clone and after installing requirements.txt modules, I run the script using python ./run_tracker.py and obtain this error : 

```
- Starting openSource Tracker v.1.3.6
+ Text Libray loaded
Traceback (most recent call last):
  File "run_tracker.py", line 4, in <module>
    run()
  File "/Users/naybu/Desktop/opensource-tracker/optracker/optracker.py", line 174, in run
    myOptracker = Optracker()
  File "/Users/naybu/Desktop/opensource-tracker/optracker/optracker.py", line 16, in __init__
    self.createRootfolder()
  File "/Users/naybu/Desktop/opensource-tracker/optracker/optracker.py", line 154, in createRootfolder
    self.createFolder(self.zero.OP_ROOT_FOLDER_PATH_VALUE)
  File "/Users/naybu/Desktop/opensource-tracker/optracker/optracker.py", line 146, in createFolder
    os.mkdir(folder)
**OSError: [Errno 30] Read-only file system: '/optracker\\'**
```

**To Reproduce**
1. Install optracker using git clone
2. Install requirements (in the optracker directory)
3. Run run_tracker.py

**Expected behavior**
I expected run_tracker to run to continue the tutorial on the readme.

**Desktop (please complete the following information):**
 - OS: Mac OS X 11.1 (Big Sur)
- Python 2.7
- Same trouble on Python 3.8

**Additional context**
I have the same issue if I install the script using PIP. Also, I installed requirements **in the optracker directory**, because I had permission issues while installing in default.

**Comment by NorseByte** [comment]
Hi,

I loooks like the problem is caused because you dont have the right priveleges.

`File "/Users/naybu/Desktop/opensource-tracker/optracker/optracker.py", line 146, in createFolder
os.mkdir(folder)
OSError: [Errno 30] Read-only file system: '/optracker\'`

This code want to create a folder for the program to run inside. And you OS (Linux, Windows etc.) dont let you do that. You need to run it with Admi priveleges. If you run linux/macos. Try:

`sudo python run_tracker.py`

If you use windows, right click on PowerShell choose run as admin and the problem should be fixed. Let me know how you do.

**Comment by naybu128** [comment]
Thank you very much for your answer, I also tried this yesterday and it comes with an error concerning PIL module : 

```
Traceback (most recent call last):
  File "run_tracker.py", line 1, in <module>
    from optracker.optracker import run
  File "/Users/naybu/Desktop/opensource-tracker/optracker/optracker.py", line 5, in <module>
    from .functions.core_func import *
  File "/Users/naybu/Desktop/opensource-tracker/optracker/functions/core_func.py", line 6, in <module>
    from PIL import Image
  File "/Users/naybu/Desktop/opensource-tracker/PIL/__init__.py", line 42
    **raise AttributeError(f"module '{__name__}' has no attribute '{name}'")**
                                                                        ^
**SyntaxError: invalid syntax**
```

Some researches on Google led me to think that it is Python version problem : PIL might not work with my Python version. I installed Pillow, which work on Python 3, but nothing change.

Is their anyway I can run optracker ignoring the image import features (which is, I think, what causes issues with PIL) ?

Thank you again for your time!

**Comment by NorseByte** [comment]
Hi, sorry for the late replay. There will come an update later on removing this error. And also the error regadring logging into Instagram now after they updated the form. In the meantime the quick fix is to remove the PIL libray. Thank for the patience.

**Comment by naybu128** [comment]
Hi, thank you very much for your response. Can't wait for this update! Thank again for your help.
